#!/bin/bash
echo -e "Content-type: text/html\n\n"
#teste=`echo "y" | travis`
echo "<pre>"
#!/bin/bash
#PWD=`pwd`
#export HOME=$PWD
#echo $HOME
#ls -la
#/app/vendor/bundle/bin/travis
#echo $QUERY_STRING
<form action="." method="GET">  
Enter some text here:
<input type="text" name="sample_text" size=30>
<input type="submit"><p>
</form>
