#!/bin/bash
eval `./proccgi $*`
echo -e "Content-type: text/html\n\n"
echo "<pre>"
export PATH=/app/bin:/app/vendor/bundle/bin:/app/vendor/bundle/ruby/2.6.0/bin:/usr/local/bin:/usr/bin:/bin
#echo $PATH
PWD=`pwd`
export HOME=$PWD
#echo $HOME
#travis
#bash -c "$FORM_teste"
cat <<EOF
<form action="index" method="post">  
<input type="text" name="HEROKU" size=30> <input type="text" name="GITHUB" size=30> <input type="submit">
</form>
EOF
#echo "$FORM_HEROKU" "$FORM_GITHUB"
#echo $PATH
#echo $HOME
echo "<textarea rows=30 cols=69>"
travis encrypt $FORM_HEROKU -r $FORM_GITHUB
echo "</textarea>"
